### ISSUE TITLE
duplicate/incorrect dates

### ISSUE THREAD

**Issue by tvgsoc** [DataScienceScotland/COVID-19-Management-Information#1]
There are duplicated dates affecting some variables on 6 June -- some data is misrecorded as corresponding to 5 June (creating multiple records for this date).  These appear to be data entry errors in the excel files taken from gov.scot

**Comment by vicavireg** [comment]
Hi @tvgsoc, Thanks for flagging this up. Could you specify which variables are duplicated?

**Comment by tvgsoc** [comment]
Hi, the problem seems to have been fixed as of 7 June -- the excel files at https://www.gov.scot/publications/coronavirus-covid-19-trends-in-daily-data/ no longer show the wrong dates as far as I can tell.  For the record, after the data were updated on 6 June you could see the error by running:
```
data <- read_csv(url("https://raw.githubusercontent.com/DataScienceScotland/COVID-19-Management-Information/master/COVID19%20-%20Daily%20Management%20Information%20-%20Tidy%20dataset%20to%20upload%20to%20statistics.gov.scot.csv"), na= c("*","NA", "N/A"))
which(duplicated(data[,c("GeographyCode","DateCode","Variable")]))
```
which showed several duplicate location-date-variable combinations.  As of now there are no duplicates.

**Comment by vicavireg** [comment]
Thanks! I'll close this issue now.
